name: Build APK (Volleyball pygame)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: System deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git zip unzip openjdk-17-jdk \
            libffi-dev libssl-dev zlib1g-dev liblzma-dev libncurses5 libncurses5-dev \
            pkg-config
      - name: Install Buildozer
        run: |
          python -m pip install --upgrade pip
          pip install "cython<3.0" buildozer==1.5.0
      - name: Build debug APK
        run: |
          buildozer android debug --verbose
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: volleyball-apk
          path: bin/*.apk
