name: Build APK (Volleyball pygame)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Java 17 for sdkmanager + Gradle
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Verify repo layout
        run: |
          echo "Root files:"; ls -la
          test -f buildozer.spec || { echo "::error::buildozer.spec missing at repo root"; exit 1; }
          test -f main.py       || { echo "::error::main.py missing at repo root"; exit 1; }

      - name: System deps
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential git zip unzip \
            libffi-dev libssl-dev zlib1g-dev liblzma-dev \
            libncurses6 libncurses-dev pkg-config wget curl

      - name: Install Android SDK + NDK
        run: |
          set -eux
          SDK="$GITHUB_WORKSPACE/android-sdk"
          mkdir -p "$SDK/cmdline-tools"
          cd "$SDK/cmdline-tools"
          curl -L -o tools.zip https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip -q tools.zip
          rm -f tools.zip
          mv cmdline-tools latest

          # Use sdkmanager (Java 17 already configured)
          export PATH="$SDK/cmdline-tools/latest/bin:$PATH"
          sdkmanager --version

          yes | sdkmanager --sdk_root="$SDK" \
            "platform-tools" "platforms;android-33" "build-tools;33.0.2" \
            "ndk;25.2.9519653" "cmdline-tools;latest"
          yes | sdkmanager --sdk_root="$SDK" --licenses

          # Compat wrappers for older Buildozer/p4a expecting $SDK/tools/bin
          mkdir -p "$SDK/tools/bin"
          cat > "$SDK/tools/bin/sdkmanager" <<'EOF'
          #!/usr/bin/env bash
          exec "$(dirname "$0")/../../cmdline-tools/latest/bin/sdkmanager" "$@"
          EOF
          chmod +x "$SDK/tools/bin/sdkmanager"
          cat > "$SDK/tools/bin/avdmanager" <<'EOF'
          #!/usr/bin/env bash
          exec "$(dirname "$0")/../../cmdline-tools/latest/bin/avdmanager" "$@"
          EOF
          chmod +x "$SDK/tools/bin/avdmanager"

          # Persist env for later steps
          {
            echo "ANDROID_SDK_ROOT=$SDK"
            echo "ANDROIDSDK=$SDK"
            echo "ANDROID_HOME=$SDK"
            echo "ANDROID_SDK_HOME=$SDK"
            echo "ANDROIDNDK=$SDK/ndk/25.2.9519653"
          } >> $GITHUB_ENV

          {
            echo "$SDK/cmdline-tools/latest/bin"
            echo "$SDK/platform-tools"
            echo "$SDK/build-tools/33.0.2"
            echo "$SDK/tools/bin"
          } >> $GITHUB_PATH

      - name: Install Buildozer
        run: |
          python -m pip install --upgrade pip
          pip install "cython<3.0" buildozer==1.5.0
          buildozer --version

      - name: Build debug APK (capture full log)
        run: |
          set -euxo pipefail
          # Ensure Java 17 for Gradle/p4a
          export JAVA_HOME="$(dirname "$(dirname "$(readlink -f "$(which javac)")")")"
          export PATH="$JAVA_HOME/bin:$PATH"
          java -version
          javac -version

          # Build and tee full output
          buildozer android debug --verbose 2>&1 | tee buildozer_full.log

          # If build failed, try to show the most useful tail
          status=${PIPESTATUS[0]} || true
          if [ "$status" != "0" ]; then
            echo "------ BUILD FAILED: tail of buildozer_full.log ------"
            tail -n 400 buildozer_full.log || true
            echo "------ GREP fatal/error from buildozer_full.log ------"
            grep -i -n -E 'error:|fatal error:|undefined reference|failed with exit code' buildozer_full.log | tail -n 200 || true
            exit $status
          fi

      - name: Upload APK artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: volleyball-apk
          path: bin/*.apk

      - name: Upload logs & .buildozer (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs-and-workdir
          path: |
            buildozer_full.log
            .buildozer/**
          if-no-files-found: warn
