name: Build APK (Volleyball pygame)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04   # jammy is stable for buildozer/p4a

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # ✅ Force Java 17 on PATH for all following steps (fixes your log)
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: System deps
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential git zip unzip \
            libffi-dev libssl-dev zlib1g-dev liblzma-dev \
            libncurses6 libncurses-dev pkg-config wget curl

      - name: Install Android SDK + NDK
        run: |
          set -eux
          SDK="$GITHUB_WORKSPACE/android-sdk"
          mkdir -p "$SDK/cmdline-tools"
          cd "$SDK/cmdline-tools"
          curl -L -o tools.zip https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip -q tools.zip
          rm -f tools.zip
          mv cmdline-tools latest

          # sdkmanager now uses Java 17 provided by setup-java
          export PATH="$SDK/cmdline-tools/latest/bin:$PATH"
          sdkmanager --version

          yes | sdkmanager --sdk_root="$SDK" \
            "platform-tools" "platforms;android-33" "build-tools;33.0.2" \
            "ndk;25.2.9519653" "cmdline-tools;latest"

          yes | sdkmanager --sdk_root="$SDK" --licenses

          # Persist for later steps
          echo "ANDROID_SDK_ROOT=$SDK" >> $GITHUB_ENV
          echo "ANDROIDSDK=$SDK" >> $GITHUB_ENV
          echo "ANDROIDNDK=$SDK/ndk/25.2.9519653" >> $GITHUB_ENV
          echo "$SDK/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$SDK/platform-tools" >> $GITHUB_PATH
          echo "$SDK/build-tools/33.0.2" >> $GITHUB_PATH

      - name: Verify layout & tools
        run: |
          echo "Repo root:"; ls -la
          test -f buildozer.spec || (echo "::error::buildozer.spec missing at repo root" && exit 1)
          echo "sdkmanager:"; which sdkmanager || true
          echo "aidl:"; which aidl || true
          echo "JAVA:"; java -version
          echo "JAVAC:"; javac -version
          echo "ANDROIDSDK=$ANDROIDSDK"
          echo "ANDROIDNDK=$ANDROIDNDK"

      - name: Install Buildozer
        run: |
          python -m pip install --upgrade pip
          pip install "cython<3.0" buildozer==1.5.0
          buildozer --version

      - name: Build debug APK
        run: |
          set -eux
          # ensure Java 17 is used by buildozer/p4a too
          export JAVA_HOME="$(dirname "$(dirname "$(readlink -f "$(which javac)")")")"
          export PATH="$JAVA_HOME/bin:$PATH"
          java -version
          javac -version
          buildozer android debug --verbose

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: volleyball-apk
          path: bin/*.apk
